using System.Collections.Generic;

namespace DigimonWorld.Frontend.WPF.Windows.Main.UserControls.CheatSheet.Models;

public static class InventoryItemCatalog
{
    public static IReadOnlyList<InventoryItemOption> Items { get; } =
    [
        new(255, "None"),
        new(0, "sm.recovery"),
        new(1, "med.recovery"),
        new(2, "lrg.recovery"),
        new(3, "sup.recovery"),
        new(4, "MP Floppy"),
        new(5, "Medium MP"),
        new(6, "Large MP"),
        new(7, "Double flop"),
        new(8, "Various"),
        new(9, "Omnipotent"),
        new(10, "Protection"),
        new(11, "Restore"),
        new(12, "Sup.restore"),
        new(13, "Bandage"),
        new(14, "Medicine"),
        new(15, "Off. Disk"),
        new(16, "Def. Disk"),
        new(17, "Hispeed dsk"),
        new(18, "Omni Disk"),
        new(19, "S.Off.disk"),
        new(20, "S.Def.disk"),
        new(21, "S.speed.disk"),
        new(22, "Auto Pilot"),
        new(23, "Off. Chip"),
        new(24, "Def. Chip"),
        new(25, "Brain Chip"),
        new(26, "Quick Chip"),
        new(27, "HP Chip"),
        new(28, "MP Chip"),
        new(29, "DV Chip A"),
        new(30, "DV Chip D"),
        new(31, "DV Chip E"),
        new(32, "Port. potty"),
        new(33, "Trn. manual"),
        new(34, "Rest pillow"),
        new(35, "Enemy repel"),
        new(36, "Enemy bell"),
        new(37, "Health shoe"),
        new(38, "Meat"),
        new(39, "Giant Meat"),
        new(40, "Sirloin"),
        new(41, "Supercarrot"),
        new(42, "Hawk radish"),
        new(43, "Spiny green"),
        new(44, "Digimushrm"),
        new(45, "Ice mushrm"),
        new(46, "Deluxmushrm"),
        new(47, "Digipine"),
        new(48, "Blue apple"),
        new(49, "Red Berry"),
        new(50, "Gold Acorn"),
        new(51, "Big Berry"),
        new(52, "Sweet Nut"),
        new(53, "Super veggy"),
        new(54, "Pricklypear"),
        new(55, "Orange bana"),
        new(56, "Power fruit"),
        new(57, "Power Ice"),
        new(58, "Speed Leaf"),
        new(59, "Sage Fruit"),
        new(60, "Muscle Yam"),
        new(61, "Calm berry"),
        new(62, "Digianchovy"),
        new(63, "Digisnapper"),
        new(64, "DigiTrout"),
        new(65, "Black trout"),
        new(66, "Digicatfish"),
        new(67, "Digiseabass"),
        new(68, "Moldy Meat"),
        new(69, "Happymushrm"),
        new(70, "Chain melon"),
        new(71, "Grey Claws"),
        new(72, "Fireball"),
        new(73, "Flamingwing"),
        new(74, "Iron Hoof"),
        new(75, "Mono Stone"),
        new(76, "Steel drill"),
        new(77, "White Fang"),
        new(78, "Black Wing"),
        new(79, "Spike Club"),
        new(80, "Flamingmane"),
        new(81, "White Wing"),
        new(82, "Torn tatter"),
        new(83, "Electo ring"),
        new(84, "Rainbowhorn"),
        new(85, "Rooster"),
        new(86, "Unihorn"),
        new(87, "Horn helmet"),
        new(88, "Scissor jaw"),
        new(89, "Fertilizer"),
        new(90, "Koga laws"),
        new(91, "Waterbottle"),
        new(92, "North Star"),
        new(93, "Red Shell"),
        new(94, "Hard Scale"),
        new(95, "Bluecrystal"),
        new(96, "Ice crystal"),
        new(97, "Hair grower"),
        new(98, "Sunglasses"),
        new(99, "Metal part"),
        new(100, "Fatal Bone"),
        new(101, "Cyber part"),
        new(102, "Mega Hand"),
        new(103, "Silver ball"),
        new(104, "Metal armor"),
        new(105, "Chainsaw"),
        new(106, "Small spear"),
        new(107, "X Bandage"),
        new(108, "Ray Gun"),
        new(109, "Gold banana"),
        new(110, "Mysty Egg"),
        new(111, "Red Ruby"),
        new(112, "Beetlepearl"),
        new(113, "Coral charm"),
        new(114, "Moon mirror"),
        new(115, "Blue Flute"),
        new(116, "old fishrod"),
        new(117, "Amazing rod"),
        new(118, "Leomonstone"),
        new(119, "Mansion key"),
        new(120, "Gear"),
        new(121, "Rain Plant"),
        new(122, "Steak"),
        new(123, "Frig Key"),
        new(124, "AS Decoder"),
        new(125, "Giga Hand"),
        new(126, "Noble Mane"),
        new(127, "Metalbanana")
    ];
}
